### ISSUE TITLE
How to launch a browser?

### ISSUE THREAD

**Issue by tjmcewan** [Niitch/gherkin-wrapper#3]
I followed the example in [an entirely new app](https://github.com/tjmcewan/gherkin-wrapper-testing), but it [won't load a browser](https://github.com/tjmcewan/gherkin-wrapper-testing/blob/main/step-definitions/example.spec.ts#L16).  I am able to launch the playwright browsers directly.

Here's the full `npx playwright test` output:

```

Running 1 test using 1 worker

  ✘  1 node_modules/gherkin-wrapper/lib/wrappers/playwright.js:74:14 › Guess the word › Breaker joins a game (158ms)


  1) node_modules/gherkin-wrapper/lib/wrappers/playwright.js:74:14 › Guess the word › Breaker joins a game

    Error: page.goto: net::ERR_ABORTED at http://localhost:3000/
    =========================== logs ===========================
    navigating to "http://localhost:3000/", waiting until "load"
    ============================================================

       at step-definitions/example.spec.ts:16

      14 | // Register step functions
      15 | wrapper.given(/the Maker has started a game with the word "(.*)"/, async ({ page, value }, { match }) => {
    > 16 |     await page.goto("http://localhost:3000/");
         |                ^
      17 | })
      18 | wrapper.when("the Breaker joins the Maker's game", () => { })
      19 | wrapper.then("the Breaker must guess a word with 5 characters", () => { })

        at ./testing/step-definitions/example.spec.ts:16:16
        at Wrapper.<anonymous> (./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:84:68)
        at ./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:8:71
        at __awaiter (./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:4:12)
        at ./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:81:72
        at Wrapper.<anonymous> (./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:81:35)
        at ./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:8:71
        at __awaiter (./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:4:12)
        at Wrapper.runStep (./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:80:16)
        at Wrapper.<anonymous> (./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:76:22)
        at ./testing/node_modules/gherkin-wrapper/lib/wrappers/playwright.js:8:71

  1 failed
    node_modules/gherkin-wrapper/lib/wrappers/playwright.js:74:14 › Guess the word › Breaker joins a game
```

Any ideas please? 🙏🏻

**Comment by Niitch** [comment]
Hi @tjmcewan, thank you for your feedback!

I just published a patch that fixes this bug.
With the updated package, the project you shared works fine.

**Comment by tjmcewan** [comment]
Confirmed working; thanks very much. :D
